### PR TITLE
🐋 Add support for multiple config files to KubeConfigWatcher

### LINKED ISSUE #344: `TestKubeConfigwatcherSubscribeModified` test is failing intermittently
The `TestKubeConfigwatcherSubscribeModified` test is failing intermittently with this error:

``` --- FAIL: TestKubeConfigWatcherSubscribeModified (0.01s)
    kube-config-watcher_test.go:57: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:57
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:201
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:60: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:60
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:201
        	Error:      	Should be true
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:57: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:57
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:202
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:60: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:60
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:202
        	Error:      	Should be true
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:57: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:57
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:203
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:60: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:60
        	            				/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:203
        	Error:      	Should be true
        	Test:       	TestKubeConfigWatcherSubscribeModified
    kube-config-watcher_test.go:204: 
        	Error Trace:	/home/runner/work/kubetail/kubetail/modules/shared/k8shelpers/kube-config-watcher_test.go:204
        	Error:      	Not equal: 
        	            	expected: "context-c7d67d76-3653-40a6-af5d-9a1b6532a923"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-context-c7d67d76-3653-40a6-af5d-9a1b6532a923
        	            	+
        	Test:       	TestKubeConfigWatcherSubscribeModified
FAIL
FAIL	github.com/kubetail-org/kubetail/modules/shared/k8shelpers	0.108s
?   	github.com/kubetail-org/kubetail/modules/shared/middleware	[no test files]
?   	github.com/kubetail-org/kubetail/modules/shared/testpb	[no test files]
?   	github.com/kubetail-org/kubetail/modules/shared/testutils	[no test files]
ok  	github.com/kubetail-org/kubetail/modules/shared/logs	1.125s
FAIL
```

### PR DESCRIPTION
**Pull request by amorey**
Fixes #344

## Summary

This PR adds support for multiple config files to KubeConfigWatcher and wraps the file system event handler with a debounce wrapper to avoid triggering multiple callbacks as part of a single config file modification write.

## Changes

- Modifies KubeConfigWatcher to provide support for multiple config files via the KUBECONFIG env var
- Adds a debounce method to KubeConfigWatcher fsnotify handler to deal with potential of multiple file events as part of a single write
- Adds unit test to KubeConfigWatcher to verify support for multiple config files
- Adds unit test to KubeConfigWatcher to verify support for file changes

## Submitter checklist

- [x] Add the correct emoji to the PR title
- [x] Link the issue number, if any, to *Fixes #*
- [x] Add summary and explain changes in the PR description
- [x] Rebase branch to HEAD
- [x] Squash changes into one signed, single commit [^1]

[^1]: See suggested [commit format](https://github.com/kubetail-org/.github/blob/main/pull-request-commit-format.md)

### CODE REVIEW

**Comment by amorey** [comment]
@bavarianbidi Here's the follow-up PR that adds multiple file support to `KubeConfigWatcher`

File: modules/shared/k8shelpers/kube-config-watcher_test.go [hunk 1]
```diff
@@ -68,26 +79,123 @@ func TestKubeConfigWatcherGet(t *testing.T) {
...
+	p2 := filepath.Join(tempDir, fmt.Sprintf("config-%s", uuid.New().String()))
+
+	// Create config files
+	cfg1, err := createKubeConfig(p1)
+	require.NoError(t, err)
+	_, err = createKubeConfig(p2)
+	require.NoError(t, err)
+
+	// Set environment
+	t.Setenv("KUBECONFIG", fmt.Sprintf("%s:%s", p1, p2))
```
Comment (rxinui) [inline modules/shared/k8shelpers/kube-config-watcher_test.go]: clientcmd has a const `RecommendedConfigPathEnvVar` that we should leverage.

File: modules/shared/k8shelpers/kube-config-watcher_test.go [hunk 2]
```diff
@@ -68,26 +79,123 @@ func TestKubeConfigWatcherGet(t *testing.T) {
...
+		p2 := filepath.Join(tempDir, fmt.Sprintf("config-%s", uuid.New().String()))
+
+		// Create config files
+		cfg1, err := createKubeConfig(p1)
+		require.NoError(t, err)
+		cfg2, err := createKubeConfig(p2)
+		require.NoError(t, err)
+
+		// Set environment
+		t.Setenv("KUBECONFIG", fmt.Sprintf("%s:%s", p1, p2))
```
Comment (rxinui) [inline modules/shared/k8shelpers/kube-config-watcher_test.go]: Same comment

File: modules/shared/k8shelpers/kube-config-watcher_test.go [hunk 3]
```diff
@@ -68,26 +79,123 @@ func TestKubeConfigWatcherGet(t *testing.T) {
 	}
 	defer os.RemoveAll(tempDir) // Clean up after test
 
-	// Create pathname
-	kubeconfigPath := filepath.Join(tempDir, fmt.Sprintf("config-%s", uuid.New().String()))
+	t.Run("single file", func(t *testing.T) {
+		// Create pathname
+		kubeconfigPath := filepath.Join(tempDir, fmt.Sprintf("config-%s", uuid.New().String()))
```
Comment (rxinui) [inline modules/shared/k8shelpers/kube-config-watcher_test.go]: Let's make it a function `NewKubeconfigFilepath` to centralise the generation. I've seen it at least 3 times in the code.

**Review by rxinui — CHANGES_REQUESTED** [review]

File: modules/shared/k8shelpers/kube-config-watcher_test.go (hunk 1 above)
Comment (amorey) [reply modules/shared/k8shelpers/kube-config-watcher_test.go]: Fixed

File: modules/shared/k8shelpers/kube-config-watcher_test.go (hunk 3 above)
Comment (amorey) [reply modules/shared/k8shelpers/kube-config-watcher_test.go]: Fixed
