### PR TITLE
Bug/240: --kubeconfig is correctly supported on serve

### LINKED ISSUE #240: bug: kubeconfig requires $HOME/.kube/config even with --kubeconfig
> also in version 0.4.3 I get this error
> 
> ````
> ❯ kubetail serve --kubeconfig /Users/alice/.kube/customkubeconfig
> 2025-05-02T14:47:22.853862+02:00 FTL ../../../../private/tmp/kubetail-20250501-6788-t9nqhl/kubetail-cli-v0.4.3/modules/cli/cmd/serve.go:110 > error="lstat /Users/alice/.kube/config: no such file or directory"
> ````
> 
> It seems to start if you you just create an empty file at /Users/alice/.kube/config
> 
> But it also does not respect the KUBECONFIG env var beause kubetail serve --kubeconfig $KUBECONFIG works but kubetail serve doesn't. 

 _Originally posted by @runningman84 in [#225](https://github.com/kubetail-org/kubetail/issues/225#issuecomment-2847129291)_

## Fix

The `Tunnel` used to serve is always looking up `$HOME/.kube/config` despite `--kubeflag`. Change this behaviour by parametizing `kubeconfig` within the Tunnel.

### PR DESCRIPTION
**Pull request by rxinui**
Fixes #240 

## Changes

`Tunnel` and `KubeconfigWatcher` now acts on `--kubeconfig` flag value. Moreover, the usage of `~` is supported.

### CODE REVIEW

File: modules/cli/cmd/logs.go [hunk 1]
```diff
@@ -522,7 +522,6 @@ func init() {
 	flagset := logsCmd.Flags()
 	flagset.SortFlags = false
 
-	flagset.String(KubeconfigFlag, "", "Path to kubeconfig file")
```
Comment (amorey) [inline modules/cli/cmd/logs.go:525]: Did you mean to remove the flag from the `logs` sub-command?

File: modules/cli/cmd/root.go [hunk 2]
```diff
@@ -18,13 +18,15 @@ import (
 	"os"
 
 	"github.com/spf13/cobra"
+	"k8s.io/client-go/tools/clientcmd"
 )
 
 const (
-	KubeconfigFlag = "kubeconfig"
+	KubeconfigFlag = clientcmd.RecommendedConfigPathFlag
```
Comment (amorey) [inline modules/cli/cmd/root.go:25]: Cool! They thought of everything

File: modules/cli/cmd/logs.go (hunk 1 above)
Comment (rxinui) [reply modules/cli/cmd/logs.go:525]: Oh sorry, i started the #225 issue and refactored this to the global PersistentFlag before switching to #240. See root.go, I haven't reverted back. I don't think it is problematic, as now it is still available.
