### PR TITLE
 ✨ Improve Linux browser dependency error handling in serve command

### LINKED ISSUE #531: Browser open error running `kubetail serve` on CentOS
When I ran `kubetail serve` on CentOS I got the following error:
```sh
$ kubetail serve
2025-07-07T18:19:16.904575014-04:00 INF Started kubetail dashboard on http://localhost:7500/
2025-07-07T18:19:16.904670265-04:00 FTL error="exec: \"xdg-open,x-www-browser,www-browser\": executable file not found in $PATH"
```

It's possible that migrating from [github.com/pkg/browser](https://pkg.go.dev/github.com/pkg/browser) to a well maintained fork might fix the problem 🤞

### PR DESCRIPTION
**Pull request by chilin0525**
Fixes #531

## Summary

* Improves error handling when the `serve` command fails to open a browser on Linux systems.

## Changes

* Improved user guidance: Provides clear installation instructions for required Linux packages (`xdg-utils`, `x-www-browser`, `www-browser`)

## Submitter checklist

- [x] Add the correct emoji to the PR title
- [x] Link the issue number, if any, to *Fixes #*
- [x] Add summary and explain changes in the PR description
- [x] Rebase branch to HEAD
- [x] Squash changes into one signed, single commit [^1]

[^1]: See suggested [commit format](https://github.com/kubetail-org/.github/blob/main/pull-request-commit-format.md)

### CODE REVIEW

File: modules/cli/cmd/serve.go [hunk 1]
```diff
@@ -164,7 +165,16 @@ var serveCmd = &cobra.Command{
 		if !skipOpen {
 			err = browser.OpenURL(fmt.Sprintf("http://%s:%d/", host, port))
 			if err != nil {
-				zlog.Warn().Err(err).Msg("Unable to open browser automatically. Please open the dashboard URL manually.")
+				if runtime.GOOS == "linux" {
+					zlog.Warn().Msgf("Unable to open browser automatically. On Linux systems, you may need to install one of the following packages:")
```
Comment (amorey) [inline modules/cli/cmd/serve.go]: Rather than splitting up the message into multiple calls to `zlog.Warn()` can you post one multi-line message using `zlog.Warn().Msg()`?

Comment (chilin0525) [reply modules/cli/cmd/serve.go]: Resolved in 059baeb

Here’s the current output:

```bash
$ ./bin/kubetail serve
2025-08-23T15:28:32.353681258+08:00 INF Started kubetail dashboard on http://localhost:7500/
2025-08-23T15:28:32.353759441+08:00 WRN Unable to open browser automatically.
                                        On Linux systems, you may need to install one of the following packages:
                                        - xdg-utils (provides xdg-open)
                                        - x-www-browser
                                        - www-browser

                                        Alternatively, you can use the --skip-open flag to skip browser opening.
                                        Please open the dashboard URL manually.
```
